from app.router import agent_router
# from app.router.root import router
from fastapi import FastAPI
from scalar_fastapi import get_scalar_api_reference
from fastapi.middleware.cors import CORSMiddleware


app = FastAPI(
    title="AI Travel Agent API",
    version="1.0.0",
    docs_url="/docs",
    redoc_url=None,
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],  # Allow your frontend origin
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# app.include_router(router, prefix="/api", tags=["api"])
app.include_router(agent_router, prefix="/api", tags=["api"])

# Expose Scalar UI for the autogenerated OpenAPI schema.

app.mount(
    "/scalar/v1",
    get_scalar_api_reference(
        openapi_url=app.openapi_url,
        title=f"{app.title} API",
    ),
)
